name: goreleaser

on:
  push:
    tags:
      - "*"
jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Copy Env
        run: |
          mv config.go.sample config.go
          mv config.json.sample config.json
      - name: Go build
        run: |
          GOOS=linux GOARCH=amd64 go build -o dist/translate *.go
          GOOS=windows GOARCH=amd64 go build -o dist/translate.exe *.go
      - uses: actions/upload-artifact@v3
        with:
          name: Upload Binalys
          path: dist/*
